######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 8 13:51:18 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
