######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 15 15:02:09 2011
######################################################################

TEMPLATE = app
TARGET = 

DEPENDPATH  += ../../utilities
INCLUDEPATH += ../../utilities \
                ../hidapi-0.6.0/hidapi
                
CONFIG      += console

# using hidapi
LIBS += -L../lib -lhidapi

# not using libhid
# LIBS += -lhid
# DEFINES += USE_LIBHID

# Input
HEADERS += testhiddevice.h \
                hiddevice.h \
                hidlistener.h
SOURCES += testhiddevice.cpp \
                hiddevice.cpp \
                hidlistener.cpp
