######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 15 15:02:09 2011
######################################################################

TEMPLATE = app
TARGET = 

DEPENDPATH  += ../../utilities
INCLUDEPATH += ../../utilities \
                ../hidapi-0.6.0/hidapi

LIBS += -L../lib -lhidapi

# Input
HEADERS += testhiddevice.h \
                hiddevice.h \
                hidlistener.h
SOURCES += testhiddevice.cpp \
                hiddevice.cpp \
                hidlistener.cpp
