######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 12 14:26:11 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

LIBS += -lhid

# Input
HEADERS += testhiddevice.h ../utilities/hiddevice.h
SOURCES += testhiddevice.cpp ../utilities/hiddevice.cpp
